Assignment/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment.DataAccess.Interfaces;
using Assignment.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RestSharp;

namespace Assignment.Controllers
{
    
    public class BookingController : Controller
    {

        private readonly IBookingRepository _bookingsRepo;
        private readonly IConfiguration _config;
        private readonly IPubSubRepository _pubSub;
        private readonly ILogRepository _log;
        private readonly IEmailRepository _email;

        public BookingController(IBookingRepository bookingsRepo, IConfiguration config, IPubSubRepository pubSub, ILogRepository log, IEmailRepository email)
        {
            _bookingsRepo = bookingsRepo;
            _config = config;
            _pubSub = pubSub;
            _log = log;
            _email = email;
        }


        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(_bookingsRepo.GetBookings());
        }
        [Authorize(Roles = "Passenger")]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Passenger")]
        [HttpPost]
        public IActionResult Create(Booking b)
        {
            try {

                //b.BookingId = 0;
                b.BookingId = _bookingsRepo.GetBookings().Count() + 1;
                b.Passenger = _bookingsRepo.GetPassenger(User.Identity.Name);
                _bookingsRepo.InsertBooking(b);

                
                string message = "Booking Id: 1\nPassenger: " + b.Passenger + "\n Location: " + b.longitude + ", " + b.latitude + "\nDestination: "+b.longitudeTo+", " + b.latitudeTo;


                IRestResponse response =  _email.SendSimpleMessage(b.Passenger.Email, message);

                
                // _pubSub.PublishEmail(User.Identity.Name, b, b.CategoryId);

            }
            catch(Exception e)
            {
                _log.Log("Error occurred in the booking process");
            }




            return RedirectToAction("Index");

        }

        
    }
}

Assignment/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Assignment.Data;
using Assignment.DataAccess.Interfaces;
using Assignment.DataAccess.Repositories;
using Assignment.Domain;
using Google.Cloud.Storage.V1;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Assignment.Controllers
{
    [Authorize(Roles = "Driver")]
    public class CarsController : Controller
    {

        private readonly ICarsRepository  _carsRepo;
        private readonly IConfiguration _config;
        private readonly ILogRepository _log;
        
        public CarsController(ICarsRepository carsRepo, IConfiguration config, ILogRepository log) 
        {
            _carsRepo = carsRepo;
            _config = config;
            _log = log;
        }
        

        public IActionResult Index()
        {
            return View(_carsRepo.GetCars());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IFormFile image, Car c)
        {
            try
            {
                
                string bucketName = _config.GetSection("AppSettings").GetSection("PicturesBucket").Value;

                string filename = Guid.NewGuid() + Path.GetExtension(image.FileName);

                c.URL = $"https://storage.googleapis.com/{bucketName}/{filename}";

                var storage = StorageClient.Create();
                using (var fileToUpload = image.OpenReadStream())
                {
                    storage.UploadObject(bucketName, filename,  null, fileToUpload);
                }

                c.Driver = _carsRepo.GetDriver(User.Identity.Name);

                
                _carsRepo.InsertCar(c);


                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                _log.Log("Failed to upload Car");
                return View();
            }
        }



        
    }
}

Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Driver"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Create">Upload Car</a>
                            </li>
                        }
                        @if (User.IsInRole("Passenger"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Create">Create Booking</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Index">Bookings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>